changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: "✨ New features"
      labels:
        - enhancement
        - feature
    - title: "🐛 Bug fixes"
      labels:
        - bug
        - fix
    - title: "🔒 Security"
      labels:
        - security
    - title: "📖 Documentation"
      labels:
        - documentation
        - docs
    - title: "🔧 Other changes"
      labels:
        - "*"
