name: Publish to npm

on:
  push:
    tags: ["v*.*.*"]

jobs:
  publish:
    name: "@sifter-ai/sdk"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - run: npm ci
        working-directory: code/sdk-ts

      - run: npm run build
        working-directory: code/sdk-ts

      - run: npm publish --access public
        working-directory: code/sdk-ts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
